const characters = [
  {name:"밥먹는 김산", grade:"일반", chance:0.001, color:"#bbb", desc:"평범하게 밥을 먹는 김산"},
  {name:"돼지 김산", grade:"일반", chance:0.001, color:"#bbb", desc:"돼지가 된 김산"},
  {name:"폭식 김산", grade:"일반", chance:0.001, color:"#bbb", desc:"폭식하는 김산"},
  {name:"소식 김산", grade:"일반", chance:0.001, color:"#bbb", desc:"소식하는 김산"},
  {name:"분식집 털이범 김산", grade:"일반", chance:0.001, color:"#bbb", desc:"분식집을 털어버린 김산"},
  {name:"비염 김산", grade:"일반", chance:0.001, color:"#ccc", desc:"비염이 있는 김산"},
  {name:"겜 하는 김산", grade:"일반", chance:0.001, color:"#ddd", desc:"게임 하는 김산"},
  {name:"화난 김산", grade:"일반", chance:0.001, color:"#eee", desc:"화가난 김산"},
  {name:"김산다라박", grade:"일반", chance:0.001, color:"#aaa", desc:"산다라박이 된 김산"},
  {name:"100kg 김산", grade:"일반", chance:0.001, color:"#bbb", desc:"김산의 현재 모습이다."},
  {name:"남산", grade:"일반", chance:0.001, color:"#ccc", desc:"남자 김산 (남산타워)"},
  {name:"먹방 vip 김산", grade:"일반", chance:0.001, color:"#ddd", desc:"항상 먹방을 보는 김산"},
  {name:"책먹는 김산", grade:"일반", chance:0.001, color:"#eee", desc:"배고픈 나머지 책도 먹는 김산"},
  {name:"길거리 음식 털이범 김산", grade:"일반", chance:0.001, color:"#aaa", desc:"길거리에서 음식을 찾는 김산"},

  {name:"멧돼지 김산", grade:"희귀", chance:0.0005, color:"#4af", desc:"김산 = 멧돼지"},
  {name:"북극곰 김산", grade:"희귀", chance:0.0005, color:"#4af", desc:"코카콜라를 마시다 북금곰이 된 김산"},
  {name:"싸움 김산", grade:"희귀", chance:0.0005, color:"#4af", desc:"배가고파 항상 싸우는 김산"},
  {name:"잠자는 김산", grade:"희귀", chance:0.0005, color:"#5af", desc:"먹고자가 된 김산"},
  {name:"춤추는 김산", grade:"희귀", chance:0.0005, color:"#6af", desc:"신이 난 나머지 춤까지 추는 김산"},
  {name:"로봇 김산", grade:"희귀", chance:0.0005, color:"#7af", desc:"쉴틈 없이 먹기위해 로봇이 된 김산"},
  {name:"마술사 김산", grade:"희귀", chance:0.0005, color:"#8af", desc:"마술로 상대 음식을 강탈하는 김산"},
  {name:"늑대인간 김산", grade:"희귀", chance:0.0005, color:"#9af", desc:"보름달이 되면 늑대인간이 되는 김산"},
  {name:"음식광 김산", grade:"희귀", chance:0.0005, color:"#aaf", desc:"평범한 김산"},
  {name:"요리왕 김산", grade:"희귀", chance:0.0005, color:"#baf", desc:"요리를 잘하는 김산"},

  {name:"공부하는 김산", grade:"초희귀", chance:0.0003, color:"#7ff", desc:"오랜만에 공부를 하는 김산"},
  {name:"급당 김산", grade:"초희귀", chance:0.0003, color:"#7ff", desc:"급식 당번이 된 김산"},

  {name:"천사 김산", grade:"에픽", chance:0.0002, color:"#a4f", desc:"천사가 된 김산"},
  {name:"악마 김산", grade:"에픽", chance:0.0002, color:"#a4f", desc:"악마가 된 김산"},
  {name:"사망한 김산", grade:"에픽", chance:0.0002, color:"#a4f", desc:"밥을 먹다 목에 걸려 죽은 김산"},
  {name:"뽀삐먹는 김산", grade:"에픽", chance:0.0002, color:"#b4f", desc:"뽀삐와 싸워 이긴 김산"},
  {name:"불타는 가오 김산", grade:"에픽", chance:0.0002, color:"#c4f", desc:"불타는 가오를 잡는 김산"},
  {name:"아이 배고파라 김산", grade:"에픽", chance:0.0002, color:"#d4f", desc:"평상시에 김산"},
  {name:"그림자도 먹은 김산", grade:"에픽", chance:0.0002, color:"#e4f", desc:"배가고파 그림자도 먹은 김산"},

  {name:"김산 누나", grade:"신화", chance:0.0001, color:"#ff6", desc:"김산의 라이벌"},
  {name:"토리코 김산", grade:"신화", chance:0.0001, color:"#ff6", desc:"토리코보다 잘먹는건 비밀"},

  {name:"각성 김산", grade:"전설", chance:0.00005, color:"#fb0", desc:"각성한 김산"},
  {name:"초분노 김산", grade:"전설", chance:0.00005, color:"#fb0", desc:"3시간 공복상태로 인해 분노게이지가 max가 된 김산"},
  {name:"에베레스트 산", grade:"전설", chance:0.00005, color:"#fb0", desc:"에베레스트 산"},
  {name:"1t 김산", grade:"전설", chance:0.00005, color:"#fb0", desc:"김산의 미래다.(1년후 미래)"},
  {name:"공부하기 싫은 김산", grade:"전설", chance:0.00005, color:"#fb0", desc:"평상시에 김산"},
  {name:"못먹는게 없는 김산", grade:"전설", chance:0.00005, color:"#fb0", desc:"평상시에 김산"},
  {name:"묠니르도 씹어먹은 김산", grade:"전설", chance:0.00005, color:"#fc0", desc:"역시 김산, 이것도 먹다니"},
  {name:"용암도 먹은 김산", grade:"전설", chance:0.00005, color:"#fd0", desc:"라바치킨처럼 먹는건가..?"},
  {name:"별까지 먹으려하는 김산", grade:"전설", chance:0.00005, color:"#fe0", desc:"김산 그건 먹는거아니야!"},

  {name:"미래 김산", grade:"초월", chance:0.00002, color:"#f0f", desc:"미래에서 온 김산"},
  {name:"무의식에 극의 김산", grade:"초월", chance:0.00002, color:"#f0f", desc:"무의식의 극의를 깨달은 김산"},
  {name:"부처 김산", grade:"초월", chance:0.00002, color:"#f0f", desc:"득도를 해버린 김산"},
  {name:"폭주 김산", grade:"초월", chance:0.00002, color:"#f0f", desc:"5시간 공복 상태로 인해 폭주했다."},

  {name:"바닷물을 전부 마셔버린 김산", grade:"시크릿", chance:0.0000000000000000001, color:"#0a1f44", desc:"목이 말라 바닷물을 모두 마신 김산"},
  {name:"무한의 뱃살 김산", grade:"시크릿", chance:0.00000000000000000000000000000000001, color:"#2e004f", desc:"결국 무한의 뱃살을 찍어버린 김산"}
];